### ISSUE TITLE
Error when LibreOffice is open

### ISSUE THREAD

**Issue by bspeice** [benbalter/word-to-markdown#56] opened 2015-06-18 22:23 UTC
When any LibreOffice program is open (tested Linux Mint with both Calc and Word) this fails with an error like the following:

```
/var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown/document.rb:91:in `read': No such file or directory - /tmp/d20150618-31341-8olz7h/some_document.html (Errno::ENOENT)
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown/document.rb:91:in `raw_html'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown/document.rb:58:in `normalized_html'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown/document.rb:20:in `tree'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown/converter.rb:78:in `semanticize_font_styles!'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown/converter.rb:18:in `convert!'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/lib/word-to-markdown.rb:31:in `initialize'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/bin/w2m:14:in `new'
	from /var/lib/gems/1.9.1/gems/word-to-markdown-1.1.3/bin/w2m:14:in `<top (required)>'
	from /usr/local/bin/w2m:23:in `load'
	from /usr/local/bin/w2m:23:in `<main>'
```

**Comment by pcssi** [comment] 2015-08-05 20:30
Can confirm this also happens on OS X `10.10.4` with LibreOffice Version: `5.0.0.5`

I had to close the terminal after closing LibreOffice in order to get `w2m` to function normally.  

I saw commit 86013700b45df10ede54a21cc719dceb46e3ae7f does a check. This is much appreciated.

**Comment by benbalter** [comment] 2015-08-05 20:37
Yes, it's a limitation of libreoffice, but https://github.com/benbalter/word-to-markdown/pull/55 should provide a descriptive error at least. I'll get a new release out that includes that fix.

**Comment by benbalter** [comment] 2015-08-05 20:39
Released https://github.com/benbalter/word-to-markdown/releases/tag/v1.1.4.

**Closed by benbalter** 2015-08-05 20:39 UTC

**Comment by pcssi** [comment] 2015-08-05 20:50
Thank you for the quick reply! The loud, descriptive error is hella helpful.

**Comment by rrjanbiah** [comment] 2016-11-25 07:33
Looks like issue is still reproducing, without descriptive error message:

    /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/document.rb:92:in `raw_html': Failed to convert /home/me/Downloads/foo.docx (WordToMarkdown::Document::ConverstionError)
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/document.rb:59:in `normalized_html'
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/document.rb:21:in `tree'
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/converter.rb:78:in `semanticize_font_styles!'
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/converter.rb:18:in `convert!'
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown.rb:45:in `initialize'
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/bin/w2m:14:in `new'
	from /var/lib/gems/2.3.0/gems/word-to-markdown-1.1.7/bin/w2m:14:in `<top (required)>'
	from /usr/local/bin/w2m:23:in `load'
	from /usr/local/bin/w2m:23:in `<main>'

**Comment by rrjanbiah** [comment] 2016-11-25 07:40
@benbalter Forgot to mention OS details:

Ubuntu
Release 16.04.1 LTS (Xenial Xerus) 32-bit
Kernel Linux 4.4.0-47-generic i686
MATE 1.12.1
